#!/bin/bash

ref_genome='/home/nilmbb/share/plants/Genomes/flax/GCA_000224295.2_ASM22429v2_genomic.fna'

if [ $# -ne 2 ]; then
  echo "Usage: $0 sample_name read1.fastq read2.fastq"
  exit 1
fi

sample_name=$1
read1=$2
read2=$3

if [ ! -f "$read1" ] || [ ! -f "$read2" ]; then
  echo "Error: input files not found"
  exit 1
fi


bwa mem "$ref_genome" "$read1" "$read2" > "$sample_name.sam"

samtools view -bS "$sample_name.sam" > "$sample_name.bam"


samtools sort "$sample_name.bam" -o "$sample_name.sorted.bam"
samtools index "$sample_name.sorted.bam"

rm "$sample_name.sam" "$sample_name.bam"

#./process_sample.sh my_sample my_read1.fastq my_read2.fastq
